title: <p align="center"> Muthu Jeyanthi Prakash </p>
description:
  <p align="center">
  <a href="profile/Prakash_resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/muthu-jeyanthi/">LinkedIn</a> |
  <a href="https://github.com/Muthu-Jeyanthi">GitHub</a>
  </p>
  
  <p align="justify">
  I am a Masters in Neuroscience graduate who enjoys applying Data Science concepts to biological data, especially Neurophysiological signals and Neuroimaging data. 
  <br><br>
  I love to learn by doing mini-projects which I've compiled under the portfolio section along with internship and hackathon projects. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
