title: <p align="center"> Muthu Jeyanthi Prakash </p>
description:
  <p align="center">
  <a href="profile/Prakash_resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/muthu-jeyanthi/">LinkedIn</a> |
  <a href="https://github.com/Muthu-Jeyanthi">GitHub</a>
  <a href="https://scholar.google.com/citations?user=abpnMRAAAAAJ&hl=en">Google Scholar</a>
  </p>
  
  <p align="justify">
  I am a PhD researcher in Computational Neuroscience at the University of TÃ¼bingen and a member of the International Max Planck Research School for Mental Mechanisms of Function and Dysfunction. My work involves human intracranial electrophysiology to study memory and visual processing. My doctoral training combines experimental neuroscience (human intracranial recordings using electrophysiology systems) with quantitative analysis of neural data. I develop python pipelines empirical analysis and visualization using human single-neuron and local field potential recordings, employing signal processing methods (such as spectral analysis and connectivity measures) alongside decoding and dimensionality reduction approaches. Broadly, my goal is to apply data science principles to understand brain function from high-dimensional neural data and to generate insights that can inform treatments for neurological and psychiatric disorders.
  </p>
  
theme: jekyll-theme-minimal
