title: Muthu Jeyanthi Prakash
description: Doctoral researcher in Computational Neuroscience
theme: minima

minima:
  skin: classic
  nav_pages:
    - index.md
    - projects.md
    - cv.md
    - blog.md


